FROM ubuntu:20.04

WORKDIR /root

# install 
RUN apt-get update && apt-get install -y git nodejs

# clone web
RUN git clone https://github.com/dinhphu2k1-gif/book-shop-web.git

# install package
RUN cd /root/book-shop-web/frontend && \ 
    npm install && \
    npm start 

# export port
EXPOSE 3000